### ISSUE TITLE
Project default not found error

### ISSUE THREAD

**Issue by Anaerin** [zabbly/incus-ui-canonical#56]
After struggling with this for a long while, I finally have Incus-UI authenticating with OIDC, but once I have successfully logged in, the UI flashes the message

> Project not found
> The project default is missing or you do not have access.
> If you think this is an error in our product, please [Report a bug](https://github.com/zabbly/incus-ui-canonical/issues/new).

then redirects to the logout, dropping you immediately back at the login page (which is a real bad idea IMHO, as it makes that error virtually unreadable)

The default project isn't missing:
```
teletran1:~# incus project show default
config:
  features.images: "true"
  features.networks: "true"
  features.networks.zones: "true"
  features.profiles: "true"
  features.storage.buckets: "true"
  features.storage.volumes: "true"
description: Default Incus project
name: default
used_by:
- /1.0/images/4b82186e181ea7181d9869bb26c28f8fcc8ba9e28930fc947c975798c6c7719e
- /1.0/networks/incusbr0
- /1.0/profiles/default
teletran1:~#
```

And as this is running in the Incus API server, it should have full access. Any idea what I'm doing wrong, or haven't set properly?

Host OS: Alpine Edge
